/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChangePassword: typeof import('./src/components/ChangePassword.vue')['default']
    CountrySelect: typeof import('./src/components/CountrySelect.vue')['default']
    DeleteAccount: typeof import('./src/components/DeleteAccount.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    PasswordTextField: typeof import('./src/components/PasswordTextField.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchTextField: typeof import('./src/components/SearchTextField.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
  }
}
